# The Docker image that will be used to build your app
image: registry.gitlab.com/pages/django:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - python manage.py migrate
    - python manage.py test
  artifacts:
    paths:
      - public
  only:
    - master