# The Docker image that will be used to build your app
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - django
  artifacts:
    paths:
      - public
  only:
    - master