# The Docker image that will be used to build your app
image: $CI_REGISTRY_IMAGE:latest

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: $CI_REGISTRY/pages/django

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  
pages:
  script:
    - python manage.py migrate
    - python manage.py test
  artifacts:
    paths:
      - public
  only:
    - master