# Generated by Django 3.2.9 on 2021-12-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
